name: Java CI with Maven

on:

  workflow_dispatch:

jobs:

  test:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 11

      uses: actions/setup-java@v2

      with:

        java-version: '11'

        distribution: 'temurin'

        cache: maven

    - name: Build with Maven

      run: mvn clean test || true

    - name: Generate Allure report
      run: mvn allure:report 
        

    - name: Set up Allure CLI
      run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.tgz
          tar -zxvf allure-2.14.0.tgz
    - name: Generate HTML report
      run: |
          ./allure-2.14.0/bin/allure generate allure-results --clean -o target/allure-report
 
    - name: Setup assets
      run: |
        mkdir public ${{ github.run_number }}
        mv target/allure-report/* ./${{ github.run_number }}/
        mv ./${{ github.run_number }} ./public/
        
    - name: Publish HTML report
      uses: actions/upload-artifact@v2
      with:
        name: allure-html-report
        path: ./public

    - name: Create directory for reports
      run: mkdir -p target/allure-reports/${{ github.run_number }}

    - name: Copy reports to deployment directory
      run: cp -R target/allure-report/* target/allure-reports/${{ github.run_number }}



    - name: Configure GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
          git -c user.name="${GITHUB_ACTOR}" -c user.email="${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout gh-pages
          git pull origin gh-pages

    - name: Deploy reports to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
          git -c user.name="${GITHUB_ACTOR}" -c user.email="${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./${{ github.run_number }}
          git commit -m "Deploy Allure reports for run ${{ github.run_number }}"
          git push origin gh-pages


          
    - name: Get repository information
      id: repo_info
      run: |
          echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          echo "::set-output name=owner::$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)"

    - name: Set environment variables
      run: |
          echo "REPO_NAME=${{ steps.repo_info.outputs.repo }}" >> $GITHUB_ENV
          echo "REPO_OWNER=${{ steps.repo_info.outputs.owner }}" >> $GITHUB_ENV

    - name: Display Allure report URL
      run: |
          echo "Allure report URL: https://${{ env.REPO_OWNER }}.github.io/${{ env.REPO_NAME }}/${{ github.run_number }}/index.html"

          
          
         
